// products.ts

type Product = {
  id: string;
  name: string;
  price: number;
  image: string;
  description: string;
  tags: string[];
};

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Headphones",
    price: 89.99,
    image: "https://via.placeholder.com/300x300?text=Headphones",
    description: "Noise-cancelling wireless headphones with long battery life.",
    tags: ["electronics", "audio", "wireless"],
  },
  {
    id: "2",
    name: "Gaming Mouse",
    price: 49.99,
    image: "https://via.placeholder.com/300x300?text=Gaming+Mouse",
    description: "Ergonomic mouse with customizable DPI and RGB lighting.",
    tags: ["electronics", "gaming", "accessory"],
  },
  {
    id: "3",
    name: "Yoga Mat",
    price: 24.99,
    image: "https://via.placeholder.com/300x300?text=Yoga+Mat",
    description: "Non-slip yoga mat for home or studio use.",
    tags: ["fitness", "yoga", "home"],
  },
  {
    id: "4",
    name: "Stainless Steel Water Bottle",
    price: 15.99,
    image: "https://via.placeholder.com/300x300?text=Water+Bottle",
    description: "Insulated water bottle keeps drinks cold for 24 hours.",
    tags: ["hydration", "outdoor", "eco-friendly"],
  },
  {
    id: "5",
    name: "Bluetooth Speaker",
    price: 39.99,
    image: "https://via.placeholder.com/300x300?text=Bluetooth+Speaker",
    description: "Portable speaker with powerful bass and waterproof design.",
    tags: ["audio", "electronics", "outdoor"],
  },
  {
    id: "6",
    name: "Leather Wallet",
    price: 34.95,
    image: "https://via.placeholder.com/300x300?text=Leather+Wallet",
    description: "Genuine leather wallet with RFID-blocking technology.",
    tags: ["accessory", "fashion", "leather"],
  },
  {
    id: "7",
    name: "Running Shoes",
    price: 69.99,
    image: "https://via.placeholder.com/300x300?text=Running+Shoes",
    description: "Lightweight and breathable shoes for running or walking.",
    tags: ["fitness", "shoes", "outdoor"],
  },
  {
    id: "8",
    name: "LED Desk Lamp",
    price: 29.99,
    image: "https://via.placeholder.com/300x300?text=LED+Desk+Lamp",
    description: "Adjustable brightness with USB charging port.",
    tags: ["home", "lighting", "office"],
  },
  {
    id: "9",
    name: "4K Action Camera",
    price: 119.99,
    image: "https://via.placeholder.com/300x300?text=Action+Camera",
    description: "Waterproof action camera for sports and travel.",
    tags: ["electronics", "camera", "adventure"],
  },
  {
    id: "10",
    name: "Mechanical Keyboard",
    price: 79.99,
    image: "https://via.placeholder.com/300x300?text=Keyboard",
    description: "RGB backlit mechanical keyboard for gamers and coders.",
    tags: ["gaming", "office", "accessory"],
  },
  {
    id: "11",
    name: "Smart Watch",
    price: 149.99,
    image: "https://via.placeholder.com/300x300?text=Smart+Watch",
    description: "Track fitness, receive notifications, and more.",
    tags: ["wearable", "electronics", "fitness"],
  },
  {
    id: "12",
    name: "Instant Coffee Maker",
    price: 59.99,
    image: "https://via.placeholder.com/300x300?text=Coffee+Maker",
    description: "Brew your favorite coffee in seconds.",
    tags: ["kitchen", "appliance", "coffee"],
  },
  {
    id: "13",
    name: "Sunglasses",
    price: 19.95,
    image: "https://via.placeholder.com/300x300?text=Sunglasses",
    description: "UV-protected polarized sunglasses for sunny days.",
    tags: ["fashion", "outdoor", "accessory"],
  },
  {
    id: "14",
    name: "Backpack",
    price: 44.99,
    image: "https://via.placeholder.com/300x300?text=Backpack",
    description: "Durable backpack for school, travel, or work.",
    tags: ["travel", "bag", "school"],
  },
  {
    id: "15",
    name: "Wireless Charger",
    price: 22.99,
    image: "https://via.placeholder.com/300x300?text=Wireless+Charger",
    description: "Fast wireless charging pad for smartphones.",
    tags: ["electronics", "charger", "mobile"],
  },
  {
    id: "16",
    name: "Standing Desk Converter",
    price: 129.99,
    image: "https://via.placeholder.com/300x300?text=Desk+Converter",
    description: "Convert any desk to a standing workstation.",
    tags: ["office", "furniture", "health"],
  },
  {
    id: "17",
    name: "HDMI Cable 6ft",
    price: 8.99,
    image: "https://via.placeholder.com/300x300?text=HDMI+Cable",
    description: "High-speed HDMI cable for 4K video and audio.",
    tags: ["electronics", "accessory", "home"],
  },
  {
    id: "18",
    name: "Electric Toothbrush",
    price: 39.99,
    image: "https://via.placeholder.com/300x300?text=Toothbrush",
    description: "Rechargeable electric toothbrush with timer.",
    tags: ["personal care", "health", "bathroom"],
  },
  {
    id: "19",
    name: "Camping Tent",
    price: 99.99,
    image: "https://via.placeholder.com/300x300?text=Camping+Tent",
    description: "Spacious waterproof tent for 2-3 people.",
    tags: ["outdoor", "camping", "travel"],
  },
  {
    id: "20",
    name: "Graphic T-Shirt",
    price: 17.99,
    image: "https://via.placeholder.com/300x300?text=Graphic+T-Shirt",
    description: "Comfortable cotton tee with stylish print.",
    tags: ["fashion", "clothing", "casual"],
  },
  {
    id: "21",
    name: "Portable Power Bank",
    price: 34.95,
    image: "https://via.placeholder.com/300x300?text=Power+Bank",
    description: "10000mAh power bank for fast charging on the go.",
    tags: ["electronics", "mobile", "travel"],
  },
  {
    id: "22",
    name: "Noise-Isolating Earbuds",
    price: 29.99,
    image: "https://via.placeholder.com/300x300?text=Earbuds",
    description: "Compact earbuds with powerful sound and mic.",
    tags: ["audio", "mobile", "accessory"],
  },
  {
    id: "23",
    name: "Resistance Bands Set",
    price: 21.95,
    image: "https://via.placeholder.com/300x300?text=Resistance+Bands",
    description: "Full set of resistance bands for home workouts.",
    tags: ["fitness", "home", "exercise"],
  },
  {
    id: "24",
    name: "Mini Projector",
    price: 149.99,
    image: "https://via.placeholder.com/300x300?text=Mini+Projector",
    description: "Portable projector for movies, presentations, and games.",
    tags: ["home", "electronics", "entertainment"],
  },
  {
    id: "25",
    name: "Essential Oil Diffuser",
    price: 27.5,
    image: "https://via.placeholder.com/300x300?text=Oil+Diffuser",
    description: "Aromatherapy diffuser with LED lights.",
    tags: ["home", "wellness", "relaxation"],
  },
  {
    id: "26",
    name: "Laptop Stand",
    price: 38.99,
    image: "https://via.placeholder.com/300x300?text=Laptop+Stand",
    description: "Adjustable aluminum laptop stand for better posture.",
    tags: ["office", "tech", "ergonomic"],
  },
  {
    id: "27",
    name: "USB-C Hub",
    price: 44.99,
    image: "https://via.placeholder.com/300x300?text=USB-C+Hub",
    description: "7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader.",
    tags: ["electronics", "accessory", "laptop"],
  },
  {
    id: "28",
    name: "Indoor Plant Set",
    price: 59.99,
    image: "https://via.placeholder.com/300x300?text=Indoor+Plants",
    description: "Set of three air-purifying indoor plants in ceramic pots.",
    tags: ["home", "decor", "plants"],
  },
  {
    id: "29",
    name: "Adjustable Dumbbells",
    price: 199.0,
    image: "https://via.placeholder.com/300x300?text=Adjustable+Dumbbells",
    description: "Space-saving dumbbells for full-body workouts.",
    tags: ["fitness", "gym", "home"],
  },
  {
    id: "30",
    name: "Wireless Security Camera",
    price: 89.99,
    image: "https://via.placeholder.com/300x300?text=Security+Camera",
    description: "Smart Wi-Fi camera with night vision and motion detection.",
    tags: ["home", "security", "electronics"],
  },
  {
    id: "31",
    name: "Bamboo Cutting Board Set",
    price: 24.99,
    image: "https://via.placeholder.com/300x300?text=Cutting+Boards",
    description: "Eco-friendly bamboo boards for all your kitchen needs.",
    tags: ["kitchen", "cooking", "eco-friendly"],
  },
  {
    id: "32",
    name: "Pet Hair Remover Roller",
    price: 16.5,
    image: "https://via.placeholder.com/300x300?text=Pet+Hair+Remover",
    description:
      "Reusable roller that removes pet hair from clothes and furniture.",
    tags: ["pet", "cleaning", "home"],
  },
  {
    id: "33",
    name: "Graphic Drawing Tablet",
    price: 69.95,
    image: "https://via.placeholder.com/300x300?text=Drawing+Tablet",
    description: "Digital pen tablet for drawing, design, and editing.",
    tags: ["design", "electronics", "creative"],
  },
  {
    id: "34",
    name: "Car Phone Mount",
    price: 13.99,
    image: "https://via.placeholder.com/300x300?text=Car+Mount",
    description: "Secure mount for smartphones in any vehicle.",
    tags: ["car", "accessory", "mobile"],
  },
  {
    id: "35",
    name: "Multitool Pocket Knife",
    price: 25.99,
    image: "https://via.placeholder.com/300x300?text=Pocket+Multitool",
    description: "Survival knife with 12 built-in tools.",
    tags: ["outdoor", "tools", "camping"],
  },
  {
    id: "36",
    name: "Magnetic Whiteboard Calendar",
    price: 18.75,
    image: "https://via.placeholder.com/300x300?text=Whiteboard+Calendar",
    description: "Organize your month with this fridge-friendly whiteboard.",
    tags: ["home", "organization", "planning"],
  },
  {
    id: "37",
    name: "Silicone Baking Mat Set",
    price: 14.99,
    image: "https://via.placeholder.com/300x300?text=Baking+Mats",
    description: "Non-stick mats for easy baking and cleanup.",
    tags: ["kitchen", "baking", "cooking"],
  },
  {
    id: "38",
    name: "Electric Milk Frother",
    price: 32.95,
    image: "https://via.placeholder.com/300x300?text=Milk+Frother",
    description: "Make café-style lattes and cappuccinos at home.",
    tags: ["kitchen", "coffee", "appliance"],
  },
  {
    id: "39",
    name: "Cordless Hair Clippers",
    price: 49.9,
    image: "https://via.placeholder.com/300x300?text=Hair+Clippers",
    description: "Rechargeable clippers with precision trimming blades.",
    tags: ["personal care", "grooming", "electronics"],
  },
  {
    id: "40",
    name: "Digital Bathroom Scale",
    price: 27.49,
    image: "https://via.placeholder.com/300x300?text=Bathroom+Scale",
    description: "Accurate body weight scale with backlit display.",
    tags: ["health", "home", "bathroom"],
  },
];
